language: objective-c
os: osx
osx_image: xcode11.6
before_install:
- openssl aes-256-cbc -K $encrypted_189e52c2c347_key -iv $encrypted_189e52c2c347_iv -in deploy_key.enc -out ./deploy_key -d
- chmod 600 ./deploy_key
- ssh-add ./deploy_key
script:
- git clone git@github.com:fumkob/certificates.git
addons:
- ssh_known_hosts: github.com
