language: objective-c
os: osx
osx_image: xcode11.6
script:
- git clone git@github.com:fumkob/certificates.git
env:
  global:
    secure: h5SQPUdBX2v2hCbCOXDu/3/lq8GTNPf2IP8gWgA5pMgjqeWaXMElOgtYc5uhClhA06b9nU3Qk0cyf9wvm4LkgcAuWk0RZlGw7HDOemLFeU/gliGkrk8utzKBFvKf8yiy4ZtNY+Cmu2XY9srpA62owWa+Itvjeyy/ZK1yFnMuGW+5tNKmFFKsNa/IiUCa+qWabmg5LamI2e8joSJMPo9E8K+iV/nkgplK2Sj8cz5mOAW7F6LNO2FxIhR0yEtxz7rFXQXJvmIKe84/llZ5B6PBG5A62HyOPsK9n+iQYh+KpcijU5py2ZFfWLJ1cnJq9KMW8Nga17yu5yhudmkuwXDuG3woLRDbMRbymIk7jLoXsm8Ef/o3hgo9exVFaA9XirtozEa9CeWEjmRP8zuncA5d0ZHkLHJrHLz7iGP4g2yijxSWGpoh1Vx1i08vTPWzKi2n0cETtChmRMY+sBTZdba5ZHsmDD8zpRTI3/qj7gJTgQdmyVta01Hm7JdoF7Rf2D3Y0CdiI/vMg8EUmMDDwIAjo+08qMImjYJ/yZjwnYu5e5fmf52xaxXa+6VLWB+2wkvMZ0wc6rFUxVIkK9r7JyWwBZB1zqNP4ziVq4qrN4izffEKYjUhmiJwR5y0MYcOoeTaWyMYpOPxEQ7sN72NIfbeURtdO2EE2QwB5Uy777UoU+w=
